# .github/workflows/schedule-debug.yml
name: schedule-debug

on:
  schedule:
    - cron: "1/20 * * * *"   # :01, :21, :41 UTC
  workflow_dispatch:          # también permite correrlo a mano

permissions:
  actions: read
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Basic event info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Schedule string: ${{ github.event.schedule }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID / Number: ${{ github.run_id }} / ${{ github.run_number }}"
          echo "Repo: ${{ github.repository }}"
          echo "Ref / SHA: ${{ github.ref }} / ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "UTC now:  $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "Local now: $(date '+%Y-%m-%d %H:%M:%S %Z')"

      - name: Checkout (to read workflow files)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Show cron declarations found
        run: |
          echo "=== every-20-min.yml (first 120 lines) ==="
          sed -n '1,120p' .github/workflows/every-20-min.yml || true
          echo "=== schedule-debug.yml (first 120 lines) ==="
          sed -n '1,120p' .github/workflows/schedule-debug.yml || true

      - name: Repo info (default branch / fork)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          curl -fsSL -H "Authorization: Bearer $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/repos/${{ github.repository }}" \
          | python - <<'PY'
import sys, json
d = json.load(sys.stdin)
print(json.dumps({k:d.get(k) for k in ["name","private","fork","default_branch"]}, indent=2))
PY

      - name: List workflows and states (enabled/disabled)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          curl -fsSL -H "Authorization: Bearer $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/repos/${{ github.repository }}/actions/workflows" \
          | python - <<'PY'
import sys, json
d = json.load(sys.stdin)
for w in d.get("workflows", []):
    print(f"- {w['name']:<25} state={w['state']}  path={w['path']}  id={w['id']}")
PY

      - name: Environment (compact)
        run: |
          env | sort | sed -n '1,120p'
