# .github/workflows/schedule-debug.yml
name: schedule-debug
on:
  schedule:
    - cron: "1/20 * * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name }}"
          echo "UTC: $(date -u '+%Y-%m-%d %H:%M:%S')"
